import Link from 'next/link';
import { ArrowRight, BadgeCheck, BriefcaseBusiness, Building2, CheckCircle2, ChevronRight, ShieldCheck, UsersRound } from 'lucide-react';
import { SearchWidget } from '@/components/SearchWidget';
import { JobCard } from '@/components/JobCard';
import { Newsletter } from '@/components/Newsletter';
import { jobs } from '@/lib/data';
export default function Home(){return <><section className="hero"><div className="hero-left"><div className="hero-content"><p className="hero-kicker"><span/> EAST AFRICA&apos;S CAREER PLATFORM</p><h1><span>Find</span> <span>Work</span> <span>That</span> <span>Moves</span> <span>East</span> <span>Africa</span> <span>Forward.</span></h1><p className="hero-copy">Find a role with purpose, build a capable team, and take the next confident step in your career.</p><SearchWidget/><div className="quick-links"><span>Explore:</span>{['Remote Jobs','Entry Level','NGO Jobs','Tech Jobs','Urgent Hiring'].map((link)=><Link href={`/jobs?q=${encodeURIComponent(link)}`} key={link}>{link}<ChevronRight size={14}/></Link>)}</div></div></div><div className="hero-visual"><img src="/images/hero-african-professionals.jpg" alt="African professionals working together in an office"/><div className="hero-visual-overlay"/><div className="hero-stat"><strong>12,000+</strong><span>professionals building their next chapter</span></div></div></section>
<section className="trust-strip"><div><BriefcaseBusiness/><span><strong>Fresh opportunities</strong>New verified roles every day</span></div><div><Building2/><span><strong>Built for employers</strong>Reach qualified East African talent</span></div><div><ShieldCheck/><span><strong>Human support</strong>Useful help when you need it</span></div></section>
<section className="section section-featured"><div className="section-heading"><div><p className="eyebrow">OPPORTUNITIES FORWARD</p><h2>Roles worth showing up for.</h2><p>New roles from teams making a difference across the region.</p></div><Link className="text-action all-jobs" href="/jobs">Browse all jobs <ArrowRight size={17}/></Link></div><div className="jobs-grid">{jobs.slice(0,6).map((job,index)=><JobCard key={job.id} job={job} index={index}/>)}</div></section>
<section className="section categories-section"><div className="section-heading"><div><p className="eyebrow">FIND YOUR SPACE</p><h2>Work, organised by what matters.</h2></div><Link className="text-action" href="/jobs">View every category <ArrowRight size={17}/></Link></div><div className="category-cards">{[{icon:BriefcaseBusiness,title:'Technology',count:'482 open roles'},{icon:Building2,title:'Finance',count:'216 open roles'},{icon:UsersRound,title:'NGO & Impact',count:'164 open roles'},{icon:BadgeCheck,title:'Healthcare',count:'89 open roles'}].map(({icon:Icon,title,count})=><Link href={`/jobs?category=${title.split(' ')[0]}`} className="category-card" key={title}><span><Icon size={22}/></span><strong>{title}</strong><small>{count}</small><ArrowRight size={18}/></Link>)}</div></section>
<section className="employer-callout"><div><p className="eyebrow">FOR EMPLOYERS</p><h2>Good people are looking. Make your next hire count.</h2><p>Post a role, meet capable candidates and manage your hiring process in one place.</p><div className="callout-actions"><Link className="button button-secondary" href="/employer/post-job">Post a Job <ArrowRight size={17}/></Link><Link className="button button-light" href="/companies">Explore companies</Link></div></div><div className="callout-panel"><CheckCircle2/><div><strong>Practical, purposeful hiring</strong><p>Reach job seekers who care about the work, not just the title.</p></div></div></section>
<section className="section impact-section"><div className="impact-image"><img src="/images/african-team.jpg" alt="African team in a collaborative conversation"/></div><div className="impact-copy"><p className="eyebrow">MORE THAN A LISTING</p><h2>Careers grow where people have useful context.</h2><p>Our guides, salary snapshots and straightforward job information help you prepare, ask better questions, and make decisions that work for your life.</p><ul><li><CheckCircle2/>Salary ranges designed for East Africa</li><li><CheckCircle2/>Career advice that respects your context</li><li><CheckCircle2/>Company information before you apply</li></ul><Link className="text-action" href="/career-advice">Read career advice <ArrowRight size={17}/></Link></div></section>
<Newsletter/></>}
