'use client';
import { useState } from 'react';
import { BarChart3, Bookmark, BriefcaseBusiness, FileText, LineChart, Mail, Settings, UserRound } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Line, LineChart as ReLineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { jobs } from '@/lib/data';
const applicationData=[{name:'Product Designer',applications:32,views:370},{name:'Programme Officer',applications:26,views:310},{name:'Financial Analyst',applications:19,views:264},{name:'Platform Engineer',applications:42,views:488}];
export function EmployerDashboard(){const tabs=[['listings','My Listings',BriefcaseBusiness],['applications','Applications',FileText],['analytics','Analytics',BarChart3],['account','Account',Settings]] as const;const [tab,setTab]=useState<typeof tabs[number][0]>('listings');return <section className="dashboard"><div className="dashboard-heading"><div><p className="eyebrow">EMPLOYER WORKSPACE</p><h1>Good morning, Mtaji Digital</h1><p>Manage open roles and the people interested in them.</p></div><a className="button button-small" href="/employer/post-job">Post a Job</a></div><div className="dashboard-tabs">{tabs.map(([value,label,Icon])=><button className={tab===value?'active':''} onClick={()=>setTab(value)} key={value}><Icon size={15}/>{label}</button>)}</div><div className="dashboard-panel">{tab==='listings'&&<Listings/>}{tab==='applications'&&<Applications/>}{tab==='analytics'&&<Analytics/>}{tab==='account'&&<Account employer/>}</div></section>}
function Listings(){return <div className="dashboard-card"><h2>My listings</h2><table className="data-table"><thead><tr><th>Role</th><th>Status</th><th>Applications</th><th>Expiry</th><th>Action</th></tr></thead><tbody>{jobs.slice(0,4).map((job,i)=><tr key={job.id}><td><a href={`/jobs/${job.slug}`}>{job.title}</a><br/><small>{job.location}</small></td><td><span className="status-pill">{i===3?'Pending payment':'Active'}</span></td><td>{[32,26,19,42][i]}</td><td>Nov {18-i*2}, 2026</td><td><button className="text-action">Edit</button></td></tr>)}</tbody></table></div>}
function Applications(){const [status,setStatus]=useState('New');return <div className="dashboard-card"><h2>Applications</h2><table className="data-table"><thead><tr><th>Candidate</th><th>Role</th><th>Applied</th><th>CV</th><th>Status</th></tr></thead><tbody>{[['Amina N.','Product Designer','Today'],['Brian K.','Software Engineer, Platform','Today'],['Grace W.','Programme Officer, Youth Employment','Yesterday'],['Joseph O.','Financial Analyst','Yesterday']].map(row=><tr key={row[0]}><td><strong>{row[0]}</strong><br/><small>{row[0].split(' ')[0].toLowerCase()}@example.com</small></td><td>{row[1]}</td><td>{row[2]}</td><td><a className="text-action" href="#">Download</a></td><td><select value={status} onChange={e=>setStatus(e.target.value)}><option>New</option><option>Reviewed</option><option>Shortlisted</option><option>Rejected</option></select></td></tr>)}</tbody></table></div>}
function Analytics(){return <><div className="stats-grid"><div className="stat-card"><strong>119</strong><span>Applications this month</span></div><div className="stat-card"><strong>1,432</strong><span>Listing views</span></div><div className="stat-card"><strong>Technology</strong><span>Top performing category</span></div></div><div className="dashboard-grid"><div className="dashboard-card"><h2>Applications per job</h2><div className="chart-box"><ResponsiveContainer width="100%" height="100%"><BarChart data={applicationData}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" tick={{fontSize:10}} interval={0}/><YAxis tick={{fontSize:11}}/><Tooltip/><Bar dataKey="applications" fill="#206dfb" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div></div><div className="dashboard-card"><h2>Views per listing</h2><div className="chart-box"><ResponsiveContainer width="100%" height="100%"><ReLineChart data={applicationData}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" tick={{fontSize:10}} hide/><YAxis tick={{fontSize:11}}/><Tooltip/><Line type="monotone" dataKey="views" stroke="#fdab44" strokeWidth={3} dot={false}/></ReLineChart></ResponsiveContainer></div></div></div></>}
function Account({employer=false}:{employer?:boolean}){return <div className="dashboard-card"><h2>{employer?'Company profile':'Your profile'}</h2><form className="profile-form"><label>{employer?'Company name':'Full name'}<input defaultValue={employer?'Mtaji Digital':'Amina Njeri'}/></label><label>Email<input defaultValue={employer?'hiring@mtaji.example':'amina@example.com'}/></label><label>{employer?'Company website':'Primary location'}<input defaultValue={employer?'https://mtaji.example':'Nairobi, Kenya'}/></label><label>{employer?'Company size':'Phone'}<input defaultValue={employer?'51–200 people':'+254 712 345 678'}/></label><label style={{gridColumn:'1/-1'}}>About<textarea rows={5} defaultValue={employer?'We build fair, human financial tools for East Africa.':'Product-minded professional with an interest in technology and impact.'}/></label><button className="button">Save changes</button></form></div>}
export function SeekerDashboard(){const tabs=[['saved','Saved Jobs',Bookmark],['applications','My Applications',FileText],['profile','Profile',UserRound],['alerts','Alerts',Mail]] as const;const [tab,setTab]=useState<typeof tabs[number][0]>('saved');return <section className="dashboard"><div className="dashboard-heading"><div><p className="eyebrow">YOUR JOB SEARCH</p><h1>Welcome back, Amina</h1><p>Keep your applications, profile and alerts working for you.</p></div><a href="/jobs" className="button button-small">Find Jobs</a></div><div className="dashboard-tabs">{tabs.map(([value,label,Icon])=><button className={tab===value?'active':''} onClick={()=>setTab(value)} key={value}><Icon size={15}/>{label}</button>)}</div><div className="dashboard-panel">{tab==='saved'&&<SavedJobs/>}{tab==='applications'&&<SeekerApplications/>}{tab==='profile'&&<Account/>}{tab==='alerts'&&<Alerts/>}</div></section>}
function SavedJobs(){return <div className="dashboard-card"><h2>Saved jobs</h2><table className="data-table"><thead><tr><th>Role</th><th>Company</th><th>Location</th><th>Deadline</th></tr></thead><tbody>{jobs.slice(0,3).map(job=><tr key={job.id}><td><a href={`/jobs/${job.slug}`}>{job.title}</a></td><td>{job.company}</td><td>{job.location}</td><td>{job.deadline}</td></tr>)}</tbody></table></div>}
function SeekerApplications(){return <div className="dashboard-card"><h2>My applications</h2><table className="data-table"><thead><tr><th>Role</th><th>Company</th><th>Applied</th><th>Status</th></tr></thead><tbody><tr><td>Product Designer</td><td>Mtaji Digital</td><td>Oct 3, 2026</td><td><span className="status-pill">Reviewed</span></td></tr><tr><td>Financial Analyst</td><td>Savannah Health</td><td>Oct 1, 2026</td><td><span className="status-pill">New</span></td></tr></tbody></table></div>}
function Alerts(){const [whatsapp,setWhatsApp]=useState(true);return <div className="dashboard-card"><h2>Job alerts</h2><p>Tell us what you want to hear about. We will send fresh matching roles by the channels you choose.</p><form className="profile-form"><label>Keywords<input defaultValue="product design, UX, fintech"/></label><label>Location<input defaultValue="Nairobi, Remote"/></label><label>Frequency<select defaultValue="Weekly"><option>Daily</option><option>Weekly</option></select></label><label className="switch-label"><input type="checkbox" checked={whatsapp} onChange={e=>setWhatsApp(e.target.checked)}/> WhatsApp notifications</label><button className="button">Save alert</button></form></div>}
