import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { CalendarDays, MapPin, BriefcaseBusiness } from 'lucide-react';
import { getJob, jobs } from '@/lib/data';
import { ApplyModal } from '@/components/ApplyModal';
import { JobCard } from '@/components/JobCard';
import { ShareJob } from '@/components/ShareJob';
export const revalidate=120;
export function generateStaticParams(){return jobs.map(job=>({slug:job.slug}))}
export function generateMetadata({params}:{params:{slug:string}}):Metadata{const job=getJob(params.slug);if(!job)return{};return {title:job.title,description:`${job.title} at ${job.company} in ${job.location}.`,openGraph:{title:`${job.title} | KaziConnect`,description:job.description}}}
export default function JobDetailPage({params}:{params:{slug:string}}){const job=getJob(params.slug);if(!job)notFound();const similar=jobs.filter(x=>x.slug!==job.slug&&(x.category===job.category||x.type===job.type)).slice(0,3);const schema={'@context':'https://schema.org','@type':'JobPosting',title:job.title,description:job.description,datePosted:'2026-10-01',validThrough:job.deadline+'T23:59:59+03:00',employmentType:job.type.toUpperCase().replace(' ','_'),hiringOrganization:{'@type':'Organization',name:job.company},jobLocation:{'@type':'Place',address:{'@type':'PostalAddress',addressLocality:job.location.split(',')[0],addressCountry:'KE'}},baseSalary:job.salary};return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><div className="page-content"><div className="job-detail-layout"><article><header className="job-detail-heading"><div className="job-detail-top"><span className="company-logo">{job.logo}</span><div><p className="job-company">{job.company}</p><h1>{job.title}</h1><p className="job-salary">{job.salary}</p></div></div><div className="detail-metadata"><span><MapPin size={16}/>{job.location}</span><span><BriefcaseBusiness size={16}/>{job.type}</span><span>Posted {job.posted}</span></div></header><Detail title="About the role"><p>{job.description}</p></Detail><Detail title="Responsibilities" values={job.responsibilities}/><Detail title="Requirements" values={job.requirements}/><Detail title="Nice to have" values={job.niceToHave}/><Detail title="Benefits" values={job.benefits}/></article><aside className="job-detail-aside"><ApplyModal jobSlug={job.slug} jobTitle={job.title}/><p className="deadline"><CalendarDays size={17}/>Application deadline: <strong>{new Date(job.deadline).toLocaleDateString('en-KE',{day:'numeric',month:'long',year:'numeric'})}</strong></p><h3>Share this job</h3><ShareJob title={`${job.title} at ${job.company}`} slug={job.slug}/></aside></div><section className="similar-jobs"><div className="section-heading"><div><p className="eyebrow">KEEP EXPLORING</p><h2>Similar opportunities</h2></div></div><div className="jobs-grid">{similar.map((item,index)=><JobCard job={item} index={index} key={item.id}/>)}</div></section></div></>}
function Detail({title,children,values}:{title:string;children?:React.ReactNode;values?:string[]}){return <section className="detail-section"><h2>{title}</h2>{children}{values&&<ul>{values.map(value=><li key={value}>{value}</li>)}</ul>}</section>}
