export type Job = {
  id: string; slug: string; title: string; company: string; companySlug: string; location: string;
  type: 'Full Time' | 'Part Time' | 'Remote' | 'Contract'; category: string; salary?: string; posted: string;
  deadline: string; featured?: boolean; description: string; responsibilities: string[]; requirements: string[];
  niceToHave: string[]; benefits: string[]; logo: string; views: number;
};

export const categories = ['Technology', 'Finance', 'NGO', 'Healthcare', 'Engineering', 'Education', 'Sales', 'Legal', 'Media', 'Government'];
export const jobTypes = ['Full Time', 'Part Time', 'Remote', 'Contract'] as const;

export const jobs: Job[] = [
  { id:'job-001', slug:'product-designer-mtaji', title:'Product Designer', company:'Mtaji Digital', companySlug:'mtaji-digital', location:'Nairobi, Kenya', type:'Full Time', category:'Technology', salary:'KES 180,000 – 240,000', posted:'2 days ago', deadline:'2026-11-18', featured:true, logo:'MD', views:684,
    description:'Mtaji Digital is building practical financial tools for East Africa. We are looking for a thoughtful Product Designer to turn complex workflows into clear, accessible experiences for people and businesses across the region.',
    responsibilities:['Lead end-to-end design from discovery and flows to high-fidelity interfaces.','Partner with product, engineering and research to validate ideas early.','Maintain and evolve our accessible, mobile-first design system.'],
    requirements:['3+ years designing digital products with a portfolio of shipped work.','Strong Figma, interaction design and user-research practice.','Clear written and verbal communication in cross-functional teams.'],
    niceToHave:['Experience in fintech or financial inclusion.','Familiarity with East African mobile-money patterns.'], benefits:['Medical cover for you and your dependants.','Learning allowance and flexible hybrid work.','Twenty-one days paid leave.'] },
  { id:'job-002', slug:'programme-officer-impact-east-africa', title:'Programme Officer, Youth Employment', company:'Impact East Africa', companySlug:'impact-east-africa', location:'Kisumu, Kenya', type:'Contract', category:'NGO', salary:'KES 130,000 – 165,000', posted:'3 days ago', deadline:'2026-11-10', featured:true, logo:'IE', views:512,
    description:'Impact East Africa is recruiting a programme officer to coordinate a youth employment portfolio with county partners, training providers and private-sector employers.', responsibilities:['Coordinate programme workplans, budgets and partner reporting.','Facilitate employer and youth engagement forums.','Track outcomes and prepare donor-quality narrative reports.'], requirements:['Bachelor’s degree in development, business or a related discipline.','Three years of programme implementation experience.','Strong reporting and stakeholder-management skills.'], niceToHave:['Experience with youth livelihoods programmes.','Working knowledge of Luo or Kiswahili.'], benefits:['Field travel support.','Wellness leave and professional development.','Inclusive, mission-led team.'] },
  { id:'job-003', slug:'financial-analyst-savannah-health', title:'Financial Analyst', company:'Savannah Health', companySlug:'savannah-health', location:'Nairobi, Kenya', type:'Full Time', category:'Finance', salary:'KES 145,000 – 190,000', posted:'5 days ago', deadline:'2026-11-05', logo:'SH', views:377,
    description:'Join Savannah Health to strengthen planning and financial insight for a growing healthcare network.', responsibilities:['Build monthly performance dashboards and forecasts.','Support budgeting and business-case analysis.','Work with operations teams to explain financial results.'], requirements:['CPA-K or ACCA finalist with a finance-related degree.','Two years of commercial finance or audit experience.','Advanced spreadsheets and presentation skills.'], niceToHave:['Experience in healthcare or multi-site operations.'], benefits:['Comprehensive medical cover.','Career pathways in a growing regional health business.'] },
  { id:'job-004', slug:'software-engineer-remote-rafiki', title:'Software Engineer, Platform', company:'Rafiki Systems', companySlug:'rafiki-systems', location:'Remote · East Africa', type:'Remote', category:'Technology', salary:'KES 220,000 – 300,000', posted:'1 week ago', deadline:'2026-11-22', logo:'RS', views:921,
    description:'Rafiki Systems is looking for a pragmatic full-stack engineer to help teams run reliable commerce operations across East Africa.', responsibilities:['Ship resilient TypeScript services and responsive web features.','Collaborate in a remote product squad with weekly planning.','Improve observability, performance and automated testing.'], requirements:['3+ years of modern JavaScript or TypeScript experience.','Experience with React and API design.','A practical approach to testing and code review.'], niceToHave:['Next.js or cloud deployment experience.','Payment or logistics domain knowledge.'], benefits:['Remote work setup allowance.','Quarterly coworking stipend.','Learning budget and annual team retreat.'] },
  { id:'job-005', slug:'communications-lead-green-horizon', title:'Communications Lead', company:'Green Horizon', companySlug:'green-horizon', location:'Arusha, Tanzania', type:'Full Time', category:'Media', salary:'USD 1,700 – 2,100', posted:'1 week ago', deadline:'2026-11-08', logo:'GH', views:289,
    description:'Green Horizon needs a strategic storyteller to make climate action accessible, credible and useful to communities and partners.', responsibilities:['Plan and deliver integrated campaign calendars.','Manage editorial production across digital channels.','Support spokesperson preparation and partner communications.'], requirements:['5+ years in strategic communications.','Excellent writing, editing and project management.','A strong portfolio of campaigns with measurable impact.'], niceToHave:['Climate, agriculture or social-impact experience.'], benefits:['Regional travel.','Medical cover and flexible work arrangements.'] },
  { id:'job-006', slug:'graduate-trainee-operations-kifaru', title:'Graduate Trainee, Operations', company:'Kifaru Logistics', companySlug:'kifaru-logistics', location:'Mombasa, Kenya', type:'Full Time', category:'Engineering', salary:'KES 55,000 – 70,000', posted:'2 weeks ago', deadline:'2026-11-14', logo:'KL', views:1103,
    description:'Start your operations career with a structured graduate programme supporting freight and warehouse teams at the Coast.', responsibilities:['Rotate through planning, fleet and warehouse functions.','Analyse daily operating metrics and propose improvements.','Support safety and customer-service initiatives.'], requirements:['Graduated within the last two years in engineering, supply chain or business.','Strong numerical and problem-solving skills.','Available to work in Mombasa.'], niceToHave:['Internship experience in logistics or manufacturing.'], benefits:['Mentoring and formal rotations.','Medical cover after probation.'] }
];

export type Company = { slug:string; name:string; industry:string; size:string; location:string; initials:string; about:string; culture:string; cover:string; };
export const companies: Company[] = [
  {slug:'mtaji-digital',name:'Mtaji Digital',industry:'Fintech',size:'51–200 people',location:'Nairobi, Kenya',initials:'MD',cover:'/images/hero-african-professionals.jpg',about:'We build fair, human financial tools for the way East Africans live and work.',culture:'Curious, practical people who test ideas with real customers and share context generously.'},
  {slug:'impact-east-africa',name:'Impact East Africa',industry:'Non-profit',size:'11–50 people',location:'Kisumu, Kenya',initials:'IE',cover:'/images/african-team.jpg',about:'A regional organisation creating pathways from learning to dignified work.',culture:'Community-led, evidence-informed, and serious about the details that make programmes work.'},
  {slug:'savannah-health',name:'Savannah Health',industry:'Healthcare',size:'201–500 people',location:'Nairobi, Kenya',initials:'SH',cover:'/images/african-briefing.jpg',about:'A connected healthcare network delivering dependable care closer to home.',culture:'Patient-first teams, continuous learning and respectful collaboration.'},
  {slug:'rafiki-systems',name:'Rafiki Systems',industry:'Software',size:'51–200 people',location:'Remote · East Africa',initials:'RS',cover:'/images/african-laptop.jpg',about:'Software infrastructure for businesses moving goods and payments across the region.',culture:'Remote by default, focused on ownership, empathy and good engineering.'},
  {slug:'green-horizon',name:'Green Horizon',industry:'Climate & Media',size:'11–50 people',location:'Arusha, Tanzania',initials:'GH',cover:'/images/professional-woman.jpg',about:'We help people understand and act on the climate opportunities around them.',culture:'Optimistic, collaborative and rooted in East African perspectives.'},
  {slug:'kifaru-logistics',name:'Kifaru Logistics',industry:'Logistics',size:'201–500 people',location:'Mombasa, Kenya',initials:'KL',cover:'/images/hero-african-professionals.jpg',about:'An integrated logistics partner connecting businesses to every major East African market.',culture:'Safety-minded, customer-obsessed teams that make progress visible every day.'}
];

export const articles = [
  {slug:'make-your-cv-work-in-east-africa',title:'Make your CV work in East Africa',excerpt:'A practical CV checklist that gives recruiters the information they need, quickly.',category:'CV Writing',author:'Wanjiku M.',date:'October 1, 2026',readTime:'6 min read',image:'/images/professional-woman.jpg'},
  {slug:'prepare-for-a-panel-interview',title:'How to prepare for a panel interview',excerpt:'Turn a multi-person interview into a focused, confident conversation.',category:'Interview Tips',author:'Kelvin O.',date:'September 27, 2026',readTime:'5 min read',image:'/images/african-team.jpg'},
  {slug:'negotiate-your-next-offer',title:'Negotiate your next offer with clarity',excerpt:'Research, language and timing for a respectful salary conversation.',category:'Salary Negotiation',author:'Amina S.',date:'September 18, 2026',readTime:'7 min read',image:'/images/african-briefing.jpg'},
  {slug:'build-a-remote-work-routine',title:'Build a remote-work routine that lasts',excerpt:'Simple boundaries and systems for productive distributed work.',category:'Remote Work',author:'Brian K.',date:'September 12, 2026',readTime:'4 min read',image:'/images/african-laptop.jpg'}
];

export const salaryRoles = [
  {role:'Software Engineer',industry:'Technology',level:'Mid-level',location:'Nairobi',low:150000,median:220000,high:320000},
  {role:'Product Designer',industry:'Technology',level:'Mid-level',location:'Nairobi',low:125000,median:185000,high:250000},
  {role:'Financial Analyst',industry:'Finance',level:'Mid-level',location:'Nairobi',low:95000,median:145000,high:210000},
  {role:'Programme Officer',industry:'NGO',level:'Mid-level',location:'Kisumu',low:85000,median:125000,high:180000},
  {role:'Graduate Trainee',industry:'Logistics',level:'Entry level',location:'Mombasa',low:45000,median:60000,high:85000}
];

export function getJob(slug:string) { return jobs.find((job) => job.slug === slug); }
export function getCompany(slug:string) { return companies.find((company) => company.slug === slug); }
