import Link from 'next/link';
import { BriefcaseBusiness, MapPin } from 'lucide-react';
import { jobs, categories } from '@/lib/data';
import { JobCard } from '@/components/JobCard';
import { PageHero } from '@/components/PageHero';
export const revalidate = 120;
export const metadata = { title:'Find Jobs' };
export default function JobsPage({searchParams}:{searchParams:{q?:string;category?:string;location?:string}}){const query=(searchParams.q??'').toLowerCase();const filtered=jobs.filter(job=>(!query||`${job.title} ${job.company} ${job.category}`.toLowerCase().includes(query))&&(!searchParams.category||job.category===searchParams.category)&&(!searchParams.location||job.location.includes(searchParams.location.split(',')[0])));return <><PageHero title="Find work that makes a difference." description="Search verified opportunities from teams hiring across East Africa."/><div className="page-content"><form className="filter-bar" action="/jobs"><label className="filter-label"><BriefcaseBusiness size={16}/>Search jobs</label><input name="q" defaultValue={searchParams.q} placeholder="Role, skill or company"/><select name="category" defaultValue={searchParams.category}><option value="">All categories</option>{categories.map(x=><option key={x}>{x}</option>)}</select><select name="location" defaultValue={searchParams.location}><option value="">Any location</option><option>Nairobi</option><option>Remote</option><option>Mombasa</option><option>Kisumu</option><option>Arusha</option></select><button className="button button-small">Search</button></form><div className="list-layout"><div><p className="results-count">{filtered.length} opportunities matching your search</p><div className="job-list">{filtered.map(job=><JobRow key={job.id} {...job}/>)}</div>{!filtered.length&&<div className="empty-state"><BriefcaseBusiness/><h2>No roles found yet</h2><p>Try another keyword, category or location. Fresh roles arrive every day.</p></div>}</div><aside className="job-sidebar"><h2>Looking for something specific?</h2><p>Explore popular searches built around real hiring needs.</p><ul><li><Link href="/jobs?category=Technology">Technology jobs</Link></li><li><Link href="/jobs?category=NGO">NGO & impact work</Link></li><li><Link href="/jobs?location=Remote">Remote opportunities</Link></li><li><Link href="/jobs?q=Graduate">Graduate roles</Link></li></ul></aside></div></div></>}
function JobRow({slug,title,company,location,type,category,salary,posted,logo}:{slug:string;title:string;company:string;location:string;type:string;category:string;salary?:string;posted:string;logo:string}){return <article className="job-row"><span className="company-logo">{logo}</span><div className="job-row-main"><p className="job-company">{company}</p><h2><Link href={`/jobs/${slug}`}>{title}</Link></h2><div className="job-meta"><span><MapPin size={14}/>{location}</span><span>Posted {posted}</span></div>{salary&&<p className="job-salary">{salary}</p>}</div><div className="job-row-right"><div className="job-tags"><span>{type}</span><span>{category}</span></div><Link className="button button-small" href={`/jobs/${slug}`}>View job</Link></div></article>}
